### ISSUE TITLE
不是有效的 Win32 應用程式，請問這是代表64位元不能執行嗎？

### ISSUE THREAD

**Issue by chaneswin** [yihong0618/bilingual_book_maker#155]
Traceback (most recent call last):
  File "C:\PythonScript\bilingual_book_maker-main20230312\make_book.py", line 1, in <module>
    from book_maker.cli import main
  File "C:\PythonScript\bilingual_book_maker-main20230312\book_maker\cli.py", line 9, in <module>
    import book_maker.obok as obok
  File "C:\PythonScript\bilingual_book_maker-main20230312\book_maker\obok.py", line 290, in <module>
    AES = _load_crypto()
          ^^^^^^^^^^^^^^
  File "C:\PythonScript\bilingual_book_maker-main20230312\book_maker\obok.py", line 283, in _load_crypto
    AES = loader()
          ^^^^^^^^
  File "C:\PythonScript\bilingual_book_maker-main20230312\book_maker\obok.py", line 220, in _load_crypto_libcrypto
    libcrypto = CDLL(libcrypto)
                ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 不是有效的 Win32 應用程式。

首先感謝開發。
请问今天下載新版以後我执行，出現了以上錯誤，不過之前的版本我是可以正常使用的，是因為我安裝的是64位元Python嗎？
拿這個錯誤訊息問過chatGPT，還安裝了64位元OpenSSL 找到 libcrypto 库，可是错误依然存在

**Comment by aszk1415** [comment]
我也遇到這樣的問題，我看出錯好像是在加入kobo的那一段代碼?

**Comment by yihong0618** [comment]
我们下午看一下。

**Comment by yihong0618** [comment]
@typebrook can you help?

**Comment by typebrook** [comment]
On Windows, `libcrypto` would be different from Unix:
https://github.com/yihong0618/bilingual_book_maker/blob/5d2c89a8414636da65465470dc1cc77fede0bf36/book_maker/obok.py#L213-L220

I wonder if corresponding lib for `libcrypto` in Windows changes. This stackoverflow post comes from 2013
https://stackoverflow.com/questions/19321982/libcrypto-equivalent-missing-on-windows

**Comment by typebrook** [comment]
Unfortunately, I don't have Windows machine.

> Since version 1.1.0 OpenSSL have changed their library names from: 
libeay32.dll -> libcrypto.dll

https://stackoverflow.com/a/55477713/7051075
https://github.com/arvidn/libtorrent/issues/1931#issue-222778628

@chaneswin Could you find `linbcrypto.dll` in your `PATH`?

**Comment by aszk1415** [comment]
> 

thanks, it works

**Comment by typebrook** [comment]
@aszk1415 So change `libeay32` into  `libcrypto` works in current Windows, right?

**Comment by aszk1415** [comment]
@typebrook  Yes, and I didn't download the libcrypto library. I just simply changed line 214 from 'libeay32' to 'libcrypto'.Thanks for your help!
