### ISSUE TITLE
我吐血了…跑了一天用CTRL+C中斷，回來不能用--resume，連個備份都沒有，哭啊

### ISSUE THREAD

**Issue by myforself** [yihong0618/bilingual_book_maker#238]
錯誤如下︰
you can resume it next time
Traceback (most recent call last):
  File "D:\bilingual_book_maker-main\book_maker\loader\txt_loader.py", line 70, in make_bilingual_book
    temp = self.translate_model.translate(batch_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilingual_book_maker-main\book_maker\translator\chatgptapi_translator.py", line 120, in translate
    t_text = self.get_translation(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilingual_book_maker-main\book_maker\translator\chatgptapi_translator.py", line 79, in get_translation
    completion = self.create_chat_completion(text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilingual_book_maker-main\book_maker\translator\chatgptapi_translator.py", line 69, in create_chat_completion
    return openai.ChatCompletion.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bilingual_book_maker-main\book_maker\loader\txt_loader.py", line 117, in _save_progress
    f.write("\n".join(self.p_to_save))
UnicodeEncodeError: 'cp950' codec can't encode character '\u521b' in position 4: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bilingual_book_maker-main\make_book.py", line 4, in <module>
    main()
  File "D:\bilingual_book_maker-main\book_maker\cli.py", line 341, in main
    e.make_bilingual_book()
  File "D:\bilingual_book_maker-main\book_maker\loader\txt_loader.py", line 89, in make_bilingual_book
    self._save_progress()
  File "D:\bilingual_book_maker-main\book_maker\loader\txt_loader.py", line 119, in _save_progress
    raise Exception("can not save resume file")
Exception: can not save resume file

求修正，關了之後甚麼都沒有，就只有個0kb的.Editing_Reality_Book.temp.bin…

**Comment by myforself** [comment]
我是用TXT跑的

**Comment by hleft** [comment]
好像是类似的编码问题 https://github.com/yihong0618/bilingual_book_maker/issues/189

**Comment by yihong0618** [comment]
@hleft 我这边修复一下。

**Comment by myforself** [comment]
> @hleft 我这边修复一下。

建議改一下說明先標上--resume暫時不對TXT起作用

**Comment by hleft** [comment]
@myforself 你试一下最新版起作用了吗

**Comment by myforself** [comment]
> @myforself 你试一下最新版起作用了吗

用 git clone https://github.com/yihong0618/bilingual_book_maker.git 更新完如下︰

remote: Enumerating objects: 684, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (31/31), done.
Receiving objects:  99% (678/684)sed 42 (delta 22), pack-reused 631
Receiving objects: 100% (684/684), 1.13 MiB | 2.81 MiB/s, done.
Resolving deltas: 100% (396/396), done.

之後用 python make_book.py --book_name test_books/booknamepart2.txt --openai_key ${不顯示KEY了} --language zh-hans 跑，用CTRL+C中斷，結果還是一樣如下︰
you can resume it next time
Traceback (most recent call last):
  File "D:\bilingual_book_maker-main\book_maker\loader\txt_loader.py", line 70, in make_bilingual_book
    temp = self.translate_model.translate(batch_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilingual_book_maker-main\book_maker\translator\chatgptapi_translator.py", line 120, in translate
    t_text = self.get_translation(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilingual_book_maker-main\book_maker\translator\chatgptapi_translator.py", line 79, in get_translation
    completion = self.create_chat_completion(text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\bilingual_book_maker-main\book_maker\translator\chatgptapi_translator.py", line 69, in create_chat_completion
    return openai.ChatCompletion.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bilingual_book_maker-main\book_maker\loader\txt_loader.py", line 117, in _save_progress
    f.write("\n".join(self.p_to_save))
UnicodeEncodeError: 'cp950' codec can't encode character '\u7f16' in position 4: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bilingual_book_maker-main\make_book.py", line 4, in <module>
    main()
  File "D:\bilingual_book_maker-main\book_maker\cli.py", line 341, in main
    e.make_bilingual_book()
  File "D:\bilingual_book_maker-main\book_maker\loader\txt_loader.py", line 89, in make_bilingual_book
    self._save_progress()
  File "D:\bilingual_book_maker-main\book_maker\loader\txt_loader.py", line 119, in _save_progress
    raise Exception("can not save resume file")
Exception: can not save resume file


還好只是試一試，不然像昨天那樣跑了半天沒存檔真的吐血…
EPUB倒是沒問題，但TXT不行。

**Comment by hleft** [comment]
不懂了.. 最新版加了utf-8但还是和之前一样的报错

**Comment by myforself** [comment]
> 不懂了.. 最新版加了utf-8但还是和之前一样的报错

你跑沒出錯？會不會是我電腦問題？你要不要跑跑看

**Comment by hleft** [comment]
@myforself  我没用过txt翻译，但txt有人没问题,有人有问题，那可能这本txt里有特殊符号，导致编码错误，或者可能是windows的编码问题（我没有windows) 复现不了..

**Comment by myforself** [comment]
> @myforself 我没用过txt翻译，但txt有人没问题,有人有问题，那可能这本txt里有特殊符号，导致编码错误，或者可能是windows的编码问题（我没有windows) 复现不了..

你跑跑看？因為出奇地用EPUB反而沒問題，這…

**Comment by hleft** [comment]
那txt发出来吧（如果没有版权问题）

**Comment by myforself** [comment]
> 那txt发出来吧（如果没有版权问题）

http://cdn.preterhuman.net/texts/movie_and_TV_scripts/transcripts/Willy%20Wonka&tChocFactory(trans).txt
你試試看

**Comment by hleft** [comment]
你直接上传自己的txt吧，我怕你本地的那个文件和我这边自己下载的编码不一样（可能我想多了）

**Comment by myforself** [comment]
> 你直接上传自己的txt吧，我怕你本地的那个文件和我这边自己下载的编码不一样（可能我想多了）

就是這個，我CTRL+A COPY下來貼上TXT丟給腳本翻的。
要做功課…

**Comment by hleft** [comment]
对啊 我是怕你在windows保存下来和其他系统编码不一样

**Comment by myforself** [comment]
> 对啊 我是怕你在windows保存下来和其他系统编码不一样

https://mab.to/t/h2bRMT5Dxrr/us2

**Comment by hleft** [comment]
@myforself  ok 我在试了 多跑一会再说

**Comment by hleft** [comment]
在linux跑了十分钟然后ctrl+c没报错 生成了TSET_bilingual_temp.txt 
![n](https://user-images.githubusercontent.com/89069008/230752298-e37ff5a2-a0e7-40e0-b920-fb645c9b66b8.png)

**Comment by myforself** [comment]
> 在linux跑了十分钟然后ctrl+c没报错 生成了TSET_bilingual_temp.txt ![n](https://user-images.githubusercontent.com/89069008/230752298-e37ff5a2-a0e7-40e0-b920-fb645c9b66b8.png)

這…我也不知道了。不過有這錯誤的不止我一個人，要不要找其他人看看？
反正是建議在簡介那改一改resume介紹啦…不然沒存檔真的痛。

**Comment by wizardforcel** [comment]
我觉得默认应该是``resume`而不是从头翻译

**Comment by yihong0618** [comment]
> 我觉得默认应该是`resume`而不是从头翻译

目前有 —resume 命令，我们看一下是不是可以同本书设置成默认
