### ISSUE TITLE
bug: 翻译test_book下的示例文件会core

### ISSUE THREAD

**Issue by figozhu** [yihong0618/bilingual_book_maker#331]
```
Traceback (most recent call last):
  File "D:\github\bilingual_book_maker\book_maker\loader\epub_loader.py", line 446, in make_bilingual_book
    index = self.process_item(
            ^^^^^^^^^^^^^^^^^^
  File "D:\github\bilingual_book_maker\book_maker\loader\epub_loader.py", line 381, in process_item
    index = self._process_paragraph(p, index, p_to_save_len)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\bilingual_book_maker\book_maker\loader\epub_loader.py", line 144, in _process_paragraph
    new_p.string = self.translate_model.translate(new_p.text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\bilingual_book_maker\book_maker\translator\chatgptapi_translator.py", line 116, in translate
    print(re.sub("\n{3,}", "\n\n", text))
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\__init__.py", line 74, in print
    return write_console.print(*objects, sep=sep, end=end)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 1672, in print
    with self:
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 2026, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 3: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\github\bilingual_book_maker\make_book.py", line 4, in <module>
    main()
  File "D:\github\bilingual_book_maker\book_maker\cli.py", line 372, in main
    e.make_bilingual_book()
  File "D:\github\bilingual_book_maker\book_maker\loader\epub_loader.py", line 458, in make_bilingual_book
    print(e)
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\__init__.py", line 74, in print
    return write_console.print(*objects, sep=sep, end=end)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 1672, in print
    with self:
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 2026, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "C:\Users\FigoZhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 3: illegal multibyte sequence
 14%|▒▒▒▒        | 44/322 [00:09<00:58,  4.76it/s]

```

**Comment by yihong0618** [comment]
will check seems the book has special unicode

**Comment by figozhu** [comment]
和使用的shell有关系。
用powershell是正常的。
但如果使用windows下的git bash的话，就会出现问题。
