### ISSUE TITLE
输入test语句无反应，直接run make_book.py出现以下错误

### ISSUE THREAD

**Issue by DKnsH** [yihong0618/bilingual_book_maker#348]
输入test语句无反应，直接run make_book.py出现以下错误
Traceback (most recent call last):
  File "e:\chatgpt\bilingual_book_maker\make_book.py", line 4, in <module>
    main()
  File "e:\chatgpt\bilingual_book_maker\book_maker\cli.py", line 260, in main
    if not os.path.isfile(options.book_name):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by yihong0618** [comment]
后面需要我跟书的路径

**Comment by DKnsH** [comment]
> 后面需要我跟书的路径

谢谢大佬，可以用了!
