### ISSUE TITLE
用别人分享的colab程式用bilingual_book_maker出现新的报错

### ISSUE THREAD

**Issue by mayichen1987** [yihong0618/bilingual_book_maker#361]
https://colab.research.google.com/drive/1zXJhFzUWRiA_NuLRZqFPVk68PQz5Z946?usp=sharing

用这个colab版本的主要原因是本地找不到合适的代理用API，怕被封
这个上周还用过没有问题，现在突然报错，代码如下：

Traceback (most recent call last):
  File "/usr/local/bin/bbook_maker", line 5, in <module>
    from book_maker.cli import main
  File "/usr/local/lib/python3.10/dist-packages/book_maker/cli.py", line 7, in <module>
    from book_maker.translator import MODEL_DICT
  File "/usr/local/lib/python3.10/dist-packages/book_maker/translator/__init__.py", line 2, in <module>
    from book_maker.translator.chatgptapi_translator import ChatGPTAPI
  File "/usr/local/lib/python3.10/dist-packages/book_maker/translator/chatgptapi_translator.py", line 7, in <module>
    import openai
  File "/usr/local/lib/python3.10/dist-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/usr/local/lib/python3.10/dist-packages/openai/types/__init__.py", line 5, in <module>
    from .edit import Edit as Edit
  File "/usr/local/lib/python3.10/dist-packages/openai/types/edit.py", line 6, in <module>
    from .._models import BaseModel
  File "/usr/local/lib/python3.10/dist-packages/openai/_models.py", line 22, in <module>
    from ._types import (
  File "/usr/local/lib/python3.10/dist-packages/openai/_types.py", line 32, in <module>
    from httpx import URL, Proxy, Timeout, Response, BaseTransport, AsyncBaseTransport
ImportError: cannot import name 'BaseTransport' from 'httpx' (/usr/local/lib/python3.10/dist-packages/httpx/__init__.py)

求修改方法，谢谢

**Comment by yihong0618** [comment]
那个应该不好用了。。。我找时间更新下

**Comment by mayichen1987** [comment]
> 那个应该不好用了。。。我找时间更新下

谢谢大佬，神奇的是我上周还用这个程式翻译了一本(*^▽^*)

**Comment by yihong0618** [comment]
> > 那个应该不好用了。。。我找时间更新下
> 
> 谢谢大佬，神奇的是我上周还用这个程式翻译了一本(_^▽^_)

是。。。我上周更新了，你可以往前退个版本。。。

**Comment by mayichen1987** [comment]
> > > 那个应该不好用了。。。我找时间更新下
> > 
> > 
> > 谢谢大佬，神奇的是我上周还用这个程式翻译了一本(_^▽^_)
> 
> 是。。。我上周更新了，你可以往前退个版本。。。

收到，这就去试一下

**Comment by mayichen1987** [comment]
> > > 那个应该不好用了。。。我找时间更新下
> > 
> > 
> > 谢谢大佬，神奇的是我上周还用这个程式翻译了一本(_^▽^_)
> 
> 是。。。我上周更新了，你可以往前退个版本。。。

  !pip -q install -U bbook_maker@git+https://github.com/yihong0618/bilingual_book_maker@2ccc918337507e3e17d6d8ef3e50963d0988d707

**Comment by mayichen1987** [comment]
> > > 那个应该不好用了。。。我找时间更新下
> > 
> > 
> > 谢谢大佬，神奇的是我上周还用这个程式翻译了一本(_^▽^_)
> 
> 是。。。我上周更新了，你可以往前退个版本。。。

https://github.com/yihong0618/bilingual_book_maker/tree/d85be6526650149db645eaba0441b5194c9e5991
这个版本可以了，谢谢Thanks♪(･ω･)ﾉ

`!pip -q install -U bbook_maker@git+https://github.com/yihong0618/bilingual_book_maker@d85be6526650149db645eaba0441b5194c9e5991`

**Comment by mayichen1987** [comment]
> > > 那个应该不好用了。。。我找时间更新下
> > 
> > 
> > 谢谢大佬，神奇的是我上周还用这个程式翻译了一本(_^▽^_)
> 
> 是。。。我上周更新了，你可以往前退个版本。。。

https://github.com/yihong0618/bilingual_book_maker/tree/d85be6526650149db645eaba0441b5194c9e5991
这个版本可以了，谢谢Thanks♪(･ω･)ﾉ

`!pip -q install -U bbook_maker@git+https://github.com/yihong0618/bilingual_book_maker@d85be6526650149db645eaba0441b5194c9e5991`

**Comment by mayichen1987** [comment]
> > > > 那个应该不好用了。。。我找时间更新下
> > > 
> > > 
> > > 谢谢大佬，神奇的是我上周还用这个程式翻译了一本(_^▽^_)
> > 
> > 
> > 是。。。我上周更新了，你可以往前退个版本。。。
> 
> https://github.com/yihong0618/bilingual_book_maker/tree/d85be6526650149db645eaba0441b5194c9e5991 这个版本可以了，谢谢Thanks♪(･ω･)ﾉ
> 
> `!pip -q install -U bbook_maker@git+https://github.com/yihong0618/bilingual_book_maker@d85be6526650149db645eaba0441b5194c9e5991`

不好意思，这周用这个版本出现新的问题了

**Comment by mayichen1987** [comment]
> > > > 那个应该不好用了。。。我找时间更新下
> > > 
> > > 
> > > 谢谢大佬，神奇的是我上周还用这个程式翻译了一本(_^▽^_)
> > 
> > 
> > 是。。。我上周更新了，你可以往前退个版本。。。
> 
> https://github.com/yihong0618/bilingual_book_maker/tree/d85be6526650149db645eaba0441b5194c9e5991 这个版本可以了，谢谢Thanks♪(･ω･)ﾉ
> 
> `!pip -q install -U bbook_maker@git+https://github.com/yihong0618/bilingual_book_maker@d85be6526650149db645eaba0441b5194c9e5991`

今天突然发现又出现问题了，这个版本也报错了，不知道该怎么改，谢谢

Traceback (most recent call last):
  File "/usr/local/bin/bbook_maker", line 5, in <module>
    from book_maker.cli import main
  File "/usr/local/lib/python3.10/dist-packages/book_maker/cli.py", line 7, in <module>
    from book_maker.translator import MODEL_DICT
  File "/usr/local/lib/python3.10/dist-packages/book_maker/translator/__init__.py", line 4, in <module>
    from book_maker.translator.deepl_free_translator import DeepLFree
  File "/usr/local/lib/python3.10/dist-packages/book_maker/translator/deepl_free_translator.py", line 9, in <module>
    from PyDeepLX import PyDeepLX
  File "/usr/local/lib/python3.10/dist-packages/PyDeepLX/PyDeepLX.py", line 15, in <module>
    from langdetect import detect
ModuleNotFoundError: No module named 'langdetect'

**Comment by mayichen1987** [comment]
经高人指点，发现先运行一遍下面的旧版，安装部分新版可能缺失的组件，再运行新版，就能用了。
如果还有错误，尝试打开/usr/local/lib/python3.10/dist-packages/googletrans/client.py文件，修改第62行
`                 proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None,`
改为
`                 proxies: typing.Dict[str, httpcore.AsyncHTTPProxy] = None,`
虽然不知道具体原因，但只要能用就行了。
最后发现这个colab程式gpt4的代码没写进去，如果有需要可以自己加进去。
