### ISSUE TITLE
`langdetect` is missing from the dependency

### ISSUE THREAD

**Issue by imWildCat** [yihong0618/bilingual_book_maker#376]
```
Traceback (most recent call last):
  File "/Users/kitten/Downloads/temp/venv/bin/bbook_maker", line 5, in <module>
    from book_maker.cli import main
  File "/Users/kitten/Downloads/temp/venv/lib/python3.11/site-packages/book_maker/cli.py", line 7, in <module>
    from book_maker.translator import MODEL_DICT
  File "/Users/kitten/Downloads/temp/venv/lib/python3.11/site-packages/book_maker/translator/__init__.py", line 4, in <module>
    from book_maker.translator.deepl_free_translator import DeepLFree
  File "/Users/kitten/Downloads/temp/venv/lib/python3.11/site-packages/book_maker/translator/deepl_free_translator.py", line 9, in <module>
    from PyDeepLX import PyDeepLX
  File "/Users/kitten/Downloads/temp/venv/lib/python3.11/site-packages/PyDeepLX/PyDeepLX.py", line 15, in <module>
    from langdetect import detect
ModuleNotFoundError: No module named 'langdetect'
```

**Comment by yihong0618** [comment]
thanks will drop PyDeepL today

**Comment by yihong0618** [comment]
fix

**Comment by imWildCat** [comment]
thank you!
