### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by asasas234** [yihong0618/bilingual_book_maker#71]
/opt/homebrew/lib/python3.10/site-packages/ebooklib/epub.py:1395: UserWarning: In the future version we will turn default option ignore_ncx to True.
  warnings.warn('In the future version we will turn default option ignore_ncx to True.')
Traceback (most recent call last):
  File "/Users/lizhibo/work/code/github/bilingual_book_maker/make_book.py", line 323, in <module>
    e = BEPUB(
  File "/Users/lizhibo/work/code/github/bilingual_book_maker/make_book.py", line 147, in __init__
    self.origin_book = epub.read_epub(self.epub_name)
  File "/opt/homebrew/lib/python3.10/site-packages/ebooklib/epub.py", line 1768, in read_epub
    book = reader.load()
  File "/opt/homebrew/lib/python3.10/site-packages/ebooklib/epub.py", line 1410, in load
    self._load()
  File "/opt/homebrew/lib/python3.10/site-packages/ebooklib/epub.py", line 1722, in _load
    self._load_opf_file()
  File "/opt/homebrew/lib/python3.10/site-packages/ebooklib/epub.py", line 1680, in _load_opf_file
    self._load_spine()
  File "/opt/homebrew/lib/python3.10/site-packages/ebooklib/epub.py", line 1659, in _load_spine
    ncxFile = self.read_file(zip_path.join(self.opf_dir, self.book.get_item_with_id(toc).get_name()))
AttributeError: 'NoneType' object has no attribute 'get_name'

**Comment by willhamlam** [comment]
test_books里面的lemo是可以正常翻译的，我自己的epub书也遇到了你这个问题

**Comment by yihong0618** [comment]
我来修复

**Comment by yihong0618** [comment]
好像不是 epub 标准格式？
可以试试用 iBooks 之类的打开么？

**Comment by willhamlam** [comment]
可以在iBooks里面打开，但是不清楚是不是因为我通过把网页的文章转成epub导致的。我用的是EpubPress的浏览器插件。

**Comment by yihong0618** [comment]
我找时间研究研究

**Comment by yihong0618** [comment]
目前不太行，需要确定的 ebooklib 能读这个，如果要修复也得给上游提 PR 了，我先关了哈

**Comment by asasas234** [comment]
> 可以在iBooks里面打开，但是不清楚是不是因为我通过把网页的文章转成epub导致的。我用的是EpubPress的浏览器插件。

我用的也是

**Comment by yihong0618** [comment]
我也试试这个插件哈

**Comment by yihong0618** [comment]
@willhamlam @asasas234 用一种比较 tricky 的方式修复了，你俩测测试试？

**Comment by yihong0618** [comment]
拉下最新代码

**Comment by willhamlam** [comment]
测试了，没问题！十分感谢🙏

**Comment by asasas234** [comment]
中午我试试
